params_example:
    ros__parameters:
        str_param: "test_string"
        d: 2.0
        i: 100
        da: [1.0, 2.2, 3.0]
        duration: 10.0
        color: red
        sub_config:
            test_int: 20
            test_double: 30.
            mode: autonomous
